version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          #install frontend modules

          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          #install backend modules

          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          #build frontend

          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          #build backend

          name: Back-End Build
          command: |
            npm run backend:build

      - run:
          #deploy frontend to aws s3 bucket

          name: Deploy Frontend
          command: |
            npm run frontend:deploy
      - run:
          #deploy backend to aws elastic beanstack

          name: Deploy Backend
          command: |
            npm run api:deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
